# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c37716ada6b6e2e94a5d6ecef20f5e1aa057daf7ac1094d45d2d089e9f24289ae4e3f35d06ef8c07c4fc271659cacbb9cbfb2b6e91bf685eaf7281ee62e888fc

test:
  secret_key_base: 04a290c4e824bbd1e534fc4ae43765e140be395b6c534f8d5c05cd56ace60bf16fe2390f29d5f3aadebf223d9d1531e9803f0d4516ef48e6007cd775bdad9a37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
